---
# tasks file for packer | Debian/Ubuntu Family

- name: Debian/Ubuntu Family | Downloading archive for {{ packer_app }} {{ packer_version }} temporarily to {{ packer_dl_loc }}
  ansible.builtin.get_url:
    url: "{{ packer_dl_url }}/{{ packer_app }}/{{ packer_version }}/{{ packer_app }}_{{ packer_version }}_{{ packer_os }}_{{ packer_architecture_map[ansible_architecture] }}.zip"
    dest: "{{ packer_dl_loc }}"

- name: Debian/Ubuntu Family | Install unzip if it is currently not in installed state
  ansible.builtin.apt:
    name: unzip
    state: present
    force_apt_get: yes
    update_cache: yes

- name: Debian/Ubuntu Family | Unarchive {{ packer_app }} {{ packer_version }}
  ansible.builtin.unarchive:
    src: "{{ packer_dl_loc }}/{{ packer_app }}_{{ packer_version }}_{{ packer_os }}_{{ packer_architecture_map[ansible_architecture] }}.zip"
    dest: "{{ packer_bin_path }}"
    owner: "{{ packer_file_owner }}"
    group: "{{ packer_file_group }}"
    mode: "{{ packer_file_mode }}"
    remote_src: true

- name: Debian/Ubuntu Family | Remove {{ packer_app }} archive file
  ansible.builtin.file:
    path: "{{ packer_dl_loc }}/{{ packer_app }}_{{ packer_version }}_{{ packer_os }}_{{ packer_architecture_map[ansible_architecture] }}.zip"
    state: absent
