---
# tasks file for packer

- name: "Downloading archive for {{ packer_app }} {{ packer_version }} temporarily to {{ packer_dl_loc }} on Debian based systems"
  get_url:
    url: "{{ packer_dl_url }}/{{ packer_app }}/{{ packer_version }}/{{ packer_app }}_{{ packer_version }}_{{ packer_osarch }}.zip"
    dest: "{{ packer_dl_loc }}"
# - name: Install python3-apt on Debian based systems, required for package_facts.
#   apt:
#     name: python3-apt
#     state: present
#     force_apt_get: yes
#     update_cache: yes
# - name: Gather package facts to verify if unzip is installed on Debian based systems
#   package_facts:
#     manager: apt
- name: Install unzip if it is currently not in installed state on Debian based systems.
  apt:
    name: unzip
    state: present
    force_apt_get: yes
    update_cache: yes
  # when: packages['unzip'] is not defined
- name: "Unarchive {{ packer_app }} on Debian based systems."
  unarchive:
    src: "{{ packer_dl_loc }}/{{ packer_app }}_{{ packer_version }}_{{ packer_osarch }}.zip"
    dest: "{{ packer_bin_path }}"
    remote_src: true
# - name: Uninstalling unzip as it was originally not in installed state on Debian based systems.
#   apt:
#     name: unzip
#     state: absent
#     force_apt_get: yes
#     update_cache: yes
#   when: packages['unzip'] is not defined
- name: "Remove {{ packer_app }} archive file from Debian based systems."
  file:
    path: "{{ packer_dl_loc }}/{{ packer_app }}_{{ packer_version }}_{{ packer_osarch }}.zip"
    state: absent
