---
# tasks file for packer | EL Family

- name: EL Family | Downloading archive for {{ packer_app }} {{ packer_version }} temporarily to {{ packer_dl_loc }}
  get_url:
    url: "{{ packer_dl_url }}/{{ packer_app }}/{{ packer_version }}/{{ packer_app }}_{{ packer_version }}_{{ packer_osarch }}.zip"
    dest: "{{ packer_dl_loc }}"

# - name: Gather package facts to verify if unzip is installed on EL based systems
#   package_facts:
#     manager: rpm

- name: EL Family | Install unzip if it is currently not in installed state
  yum:
    name: unzip
    state: present
    update_cache: yes
    # when: packages['unzip'] is not defined

- name: EL Family | {{ packer_app }}_unarchive
  unarchive:
    src: "{{ packer_dl_loc }}/{{ packer_app }}_{{ packer_version }}_{{ packer_osarch }}.zip"
    dest: "{{ packer_bin_path }}"
    remote_src: true

# - name: Uninstalling unzip from Debian based systems as it was originally not in installed state
#   yum:
#     name: unzip
#     state: absent
#   when: packages['unzip'] is not defined

- name: EL Family | Remove {{ packer_app }} archive
  file:
    path: "{{ packer_dl_loc }}/{{ packer_app }}_{{ packer_version }}_{{ packer_osarch }}.zip"
    state: absent
