---
# tasks file for packer | EL Family

- name: EL Family | Downloading archive for {{ packer_app }} {{ packer_version }} temporarily to {{ packer_dl_loc }}
  ansible.builtin.get_url:
    url: "{{ packer_dl_url }}/{{ packer_app }}/{{ packer_version }}/{{ packer_app }}_{{ packer_version }}_{{ packer_os }}_{{ packer_arch }}.zip"
    dest: "{{ packer_dl_loc }}"


- name: EL Family | Install unzip if it is currently not in installed state
  ansible.builtin.yum:
    name: unzip
    state: present
    update_cache: yes

- name: EL Family | Unarchive {{ packer_app }} {{ packer_version }}
  ansible.builtin.unarchive:
    src: "{{ packer_dl_loc }}/{{ packer_app }}_{{ packer_version }}_{{ packer_os }}_{{ packer_arch }}.zip"
    dest: "{{ packer_bin_path }}"
    owner: "{{ packer_file_owner }}"
    group: "{{ packer_file_group }}"
    mode: "{{ packer_file_mode }}"
    remote_src: true

- name: EL Family | Remove {{ packer_app }} archive
  ansible.builtin.file:
    path: "{{ packer_dl_loc }}/{{ packer_app }}_{{ packer_version }}_{{ packer_os }}_{{ packer_arch }}.zip"
    state: absent
